version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/eleaning
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_DB=TestMicroservice
    depends_on:
      - mongo
      - mysql

  mongo:
    image: mongo
    ports:
      - '27017:27017'

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: TestMicroservice
    ports:
      - '3306:3306'